esphome:
  name: solar_tracker1
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "SSID"
  password: "PasswordWifi"
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 172.16.2.16
    # Set this to the IP address of the router. Often ends with .1
    gateway: 172.16.2.254
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0
    dns1: 172.16.110.253
    dns2: 172.16.110.57

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "traker"
    password: "PasswordWifi"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "PasswordApi"

ota:
  password: "passwordOta"

sun:
  latitude: 49.629444
  longitude: 22.161389

  time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Warsaw
    servers:
      - 172.16.110.253
      - time.google.com
  - platform: homeassistant  

i2c:
    sda: D3
    scl: D4
    scan: True
  
sensor:
  - platform: sun
    name: Wysokość słońca
    type: elevation
  - platform: sun
    name: Azymut słońca
    type: azimuth    
  - platform: qmc5883l
    address: 0x0D
    field_strength_x:
      name: "QMC5883L Field Strength X"
    field_strength_y:
      name: "QMC5883L Field Strength Y"
    field_strength_z:
      name: "QMC5883L Field Strength Z"
    heading:
      name: "QMC5883L Heading"
    range: 200uT
    oversampling: 512x
    update_interval: 5s
  - platform: wifi_signal
    name: "Traker 1 WiFi Signal"
    update_interval: 60s

switch:
  - platform: gpio
    pin: D8
    name: "prawo"
    id: prawo
  - platform: gpio
    pin: D7
    name: "lewo"
    id: lewo
  - platform: gpio    
    pin: D6
    name: "gora"
    id: gora
  - platform: gpio    
    pin: D5
    name: "dol"
    id: dol    
    
web_server:
  port: 80
  auth:
    username: admin
    password: PasswordWeb
